# 电池电量报告间隔时间单位是秒
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# 增加键盘消抖
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# 增加键盘的 BLE 无线电的发射功率，用解决延迟和左右通讯不佳的问题
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 更改键盘默认显示名称
CONFIG_ZMK_KEYBOARD_NAME="ERGO Mini"

CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# 禁用外部电源关闭修复显示器会随灯关闭的问题，临时解决办法
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# 修复iPadOS/macOS兼容性问题,开启后音乐音量等媒体按键在无线模式下在某些系统上会失效
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=n

# 组合按键最大数量
CONFIG_ZMK_COMBO_MAX_PRESSED_COMBOS=15
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=15

# 是否开启蓝牙链接密码
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n

# 启用键盘RGB功能
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=30

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
